---
# Variables common to all Cisco routers
ansible_network_os: ios
ansible_connection: network_cli
ansible_become: yes
ansible_user: admin
ansible_password: admin_password           # Use vault or other means to store credentails
ansible_become_method: enable
ansible_become_password: admin_password    # Use vault or other means to store credentails